paths:
  /api/products:
    get:
      sumary: Get all products
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1  
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1  
        - name: sort
          in: query
          example: asc desc
          schema:
            type: string
            minimum: 1  
        - name: query
          in: query
          schema:
            type: string
            minimum: 1  
      responses:
        '200':
          description: All products found
        '400':
          description: Some data is missing
        '500':
          description: Server error
      tags:
        - Products
    post:
      sumary: Add one product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
            algo: algo
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Error. Missing info
        '401':
          description: Unauthorized
        '500':
          description: Server error
      tags:
        - Products
  /api/products/{id}:
    get:
      sumary: Get one product by ID
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        '200':
          description: One product found
        '400':
          description: Product doesn't exist
        '500':
          description: Server error
      tags:
        - Products
    put:
      sumary: Update one product
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        '201':
          description: Product updated successfully
        '400':
          description: Error. The product doesn't exist.
        '401':
          description: Unauthorized
        '500':
          description: Server error
      tags:
        - Products
    delete:
      sumary: Update one product
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        '204':
          description: Product deleted successfully
        '400':
          description: Error. The product doesn't exist.
        '401':
          description: Unauthorized
        '500':
          description: Server error
      tags:
        - Products
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
        title: 
          type: string
        description: 
          type: string
        price: 
          type: number
        thumbnail: 
          type: string
        code: 
          type: string
        stock: 
          type: number
        category: 
          type: string
        status: 
          type: boolean
        owner: 
          type: string
      